import tkinter as tk


def make_button(root=None,
                text="Click Me",
                command=None,
                activebackground="blue",
                activeforeground="white",
                anchor="center",
                bd=3,
                bg="lightgray",
                cursor="hand2",
                disabledforeground="gray",
                fg="black",
                font=("Arial", 12),
                height=2,
                highlightbackground="black",
                highlightcolor="green",
                highlightthickness=2,
                justify="center",
                overrelief="raised",
                padx=10,
                pady=5,
                width=15,
                wraplength=100):
    button = tk.Button(root,
                       text=text,
                       command=lambda: command(root),
                       activebackground=activebackground,
                       activeforeground=activeforeground,
                       anchor=anchor,
                       bd=bd,
                       bg=bg,
                       cursor=cursor,
                       disabledforeground=disabledforeground,
                       fg=fg,
                       font=font,
                       height=height,
                       highlightbackground=highlightbackground,
                       highlightcolor=highlightcolor,
                       highlightthickness=highlightthickness,
                       justify=justify,
                       overrelief=overrelief,
                       padx=padx,
                       pady=pady,
                       width=width,
                       wraplength=wraplength)
    return button
